CREATE TABLE Users (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  Name NVARCHAR(100) NOT NULL,
  Email NVARCHAR(255) NOT NULL UNIQUE,
  PasswordHash NVARCHAR(255) NOT NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE()
);

CREATE TABLE Products (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  Title NVARCHAR(200) NOT NULL,
  Description NVARCHAR(MAX) NULL,
  Price DECIMAL(10,2) NOT NULL,
  ImageUrl NVARCHAR(500) NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE()
);
